on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Configurar python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.8'

            - name: Ejecutar aplicación
              run: python main.py
            